---
- name: Include OS-specific variables.
  ansible.builtin.include_vars: "{{ ansible_os_family }}.yml"

# Fail2Ban
- ansible.builtin.include_tasks: fail2ban.yml
  when: security_fail2ban_enabled | bool

# SSH
- ansible.builtin.include_tasks: ssh.yml

# Autoupdate
- ansible.builtin.include_tasks: autoupdate-RedHat.yml
  when:
    - ansible_os_family == 'RedHat'
    - security_autoupdate_enabled | bool

- ansible.builtin.include_tasks: autoupdate-Debian.yml
  when:
    - ansible_os_family == 'Debian'
    - security_autoupdate_enabled | bool
